apply plugin: 'com.android.application'

android {
    namespace "com.github.yeriomin.smsscheduler"
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.github.yeriomin.smsscheduler"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 5
        versionName "0.5"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig true
    }

    lintOptions {
        disable 'GoogleAppIndexingWarning','GoogleAppIndexingApiWarning','MissingTranslation'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}